### ISSUE TITLE
Main section

### ISSUE THREAD

**Issue by Tereseus** [n-k-f/ColmarAcademy#1]
You don't need a main section, your div class main makes the your html not wide enough. If you got rid of it, it would fill the whole page instead of 70% of the page. Please take a look at how your repo looks and how the solution looks. This is a quick fix and your repo actually works perfectly with the console open so maybe that is why you put it in. You can take it out now though.

![image](https://user-images.githubusercontent.com/19315896/34802223-63d21a90-f63a-11e7-9eb0-dcd9353448cc.png)

**Comment by n-k-f** [comment]
Thanks so much for this feedback - perhaps I didn't catch this because I was on a smaller screen. (I have my Inspect window showing up horizontally instead of vertically.)

This is now fixed.
